In [1]:
import topogenesis as tg
import numpy as np
np.random.seed(0)

In [2]:
# agent class
class agent():
    def __init__(self, origin, stencil):
        self.origin = np.array(origin).astype(np.int8)
        self.stencil = stencil
    def walk(self, env):
        # find available spaces
        neighs = env.availibility.find_neighbours_masked(self.stencil, loc = self.origin)
        #find availability of neighbours
        neighs_avail = env.availibility.flatten()[neighs]
        # mask of available neighbours
        mask = np.argwhere(neighs_avail==1).flatten()
        # random choice of available neighbours 
        selected_neigh = neighs[np.random.choice(mask, 1)]
        
        # update information
        self.origin = np.array(np.unravel_index(selected_neigh, env.availibility.shape)).flatten()

# initiate availibility lattice
unit = 1
bounds = np.array([[0,0,0],[0,7,7]])
avail_lattice = tg.lattice(bounds, unit=unit, default_value=1, dtype=int)

# randomly scattering the agents
selected_cells = np.random.choice(avail_lattice.size, 5)
agent_ind = np.array(np.unravel_index(selected_cells, avail_lattice.shape))

# creating neighborhood definition
stencil = tg.stencil(np.array([[[0, 1, 0,],
                                [1, 0, 1,],
                                [0, 1, 0,]]]),origin=np.array([0,1,1]))


agents= []
# creating agent objects
for ind in agent_ind.T.tolist():
    myagent = agent(ind, stencil)
    agents.append(myagent)

In [3]:
# environment class
class environment():
    def __init__(self, lattices, agents):
        self.availibility = lattices["availibility"]
        self.agents = agents
    
    def update_availability(self):
        for a in self.agents:
            self.availibility[tuple(a.origin)] *= 0
    
    def walk_agents(self):
        for a in self.agents:
            a.walk(self)
        

# initiate the environment
env_lattices = {"availibility": avail_lattice}
env = environment(env_lattices, agents)
print(env.availibility)
env.update_availability()
print(env.availibility)
env.walk_agents()
env.update_availability()
print(env.availibility)
env.walk_agents()
env.update_availability()
print(env.availibility)

[[[1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]]]
[[[0 1 1 0 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 0 1 1 0]
  [1 1 1 1 1 0 1 1]
  [1 1 1 1 1 1 1 1]]]
[[[0 1 1 0 1 1 1 1]
  [0 1 1 1 0 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 0 1 1 0]
  [1 1 1 1 0 0 1 0]
  [1 1 1 1 1 0 1 1]]]
[[[0 1 1 0 1 1 1 1]
  [0 1 1 1 0 0 1 1]
  [1 0 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 0 1 1 0]
  [1 1 1 1 0 0 1 0]
  [1 1 1 1 0 0 1 0]]]
